version: 0.0

os: linux
files:
   - source: /
     destination: /tmp
permissions:
   - object: /tmp
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file

hooks:
   BeforeInstall:
   - location: Scripts/deploy.sh
     runas: root
   AfterInstall:
   - location: Scripts/runjar.sh
     runas: root
