version: 0.0

os: linux
files:
   - source: /
     destination: /tmp/myapp-new/
permissions:
   - object: /tmp/myapp-new
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - directory
hooks:
   BeforeInstall:
   - location: /tmp/myapp-new/Scripts/deploy.sh
     runas: root
   AfterInstall:
   - location: /tmp/myapp-new/Scripts/runjar.sh
     runas: root
